/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppContractRouteImport } from './routes/_app/contract'
import { Route as AppDataRouteImport } from './routes/_app/data'
import { Route as AppDesktopRouteImport } from './routes/_app/desktop'
import { Route as AppEvalRouteImport } from './routes/_app/eval'
import { Route as AppLibraryRouteImport } from './routes/_app/library'
import { Route as AppPlayRouteImport } from './routes/_app/play'
import { Route as HarnessTaskIdRouteImport } from './routes/harness.$taskId'
import { Route as WorldsTaskIdRouteImport } from './routes/worlds.$taskId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppContractRoute = AppContractRouteImport.update({
  id: '/contract',
  path: '/contract',
  getParentRoute: () => AppRoute,
} as any)
const AppDataRoute = AppDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AppRoute,
} as any)
const AppDesktopRoute = AppDesktopRouteImport.update({
  id: '/desktop',
  path: '/desktop',
  getParentRoute: () => AppRoute,
} as any)
const AppEvalRoute = AppEvalRouteImport.update({
  id: '/eval',
  path: '/eval',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppPlayRoute = AppPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => AppRoute,
} as any)
const HarnessTaskIdRoute = HarnessTaskIdRouteImport.update({
  id: '/harness/$taskId',
  path: '/harness/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldsTaskIdRoute = WorldsTaskIdRouteImport.update({
  id: '/worlds/$taskId',
  path: '/worlds/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/contract': typeof AppContractRoute
  '/data': typeof AppDataRoute
  '/desktop': typeof AppDesktopRoute
  '/eval': typeof AppEvalRoute
  '/library': typeof AppLibraryRoute
  '/play': typeof AppPlayRoute
  '/harness/$taskId': typeof HarnessTaskIdRoute
  '/worlds/$taskId': typeof WorldsTaskIdRoute
}
export interface FileRoutesByTo {
  '/contract': typeof AppContractRoute
  '/data': typeof AppDataRoute
  '/desktop': typeof AppDesktopRoute
  '/eval': typeof AppEvalRoute
  '/library': typeof AppLibraryRoute
  '/play': typeof AppPlayRoute
  '/harness/$taskId': typeof HarnessTaskIdRoute
  '/worlds/$taskId': typeof WorldsTaskIdRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/contract': typeof AppContractRoute
  '/_app/data': typeof AppDataRoute
  '/_app/desktop': typeof AppDesktopRoute
  '/_app/eval': typeof AppEvalRoute
  '/_app/library': typeof AppLibraryRoute
  '/_app/play': typeof AppPlayRoute
  '/harness/$taskId': typeof HarnessTaskIdRoute
  '/worlds/$taskId': typeof WorldsTaskIdRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contract'
    | '/data'
    | '/desktop'
    | '/eval'
    | '/library'
    | '/play'
    | '/harness/$taskId'
    | '/worlds/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/contract'
    | '/data'
    | '/desktop'
    | '/eval'
    | '/library'
    | '/play'
    | '/harness/$taskId'
    | '/worlds/$taskId'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/contract'
    | '/_app/data'
    | '/_app/desktop'
    | '/_app/eval'
    | '/_app/library'
    | '/_app/play'
    | '/harness/$taskId'
    | '/worlds/$taskId'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  HarnessTaskIdRoute: typeof HarnessTaskIdRoute
  WorldsTaskIdRoute: typeof WorldsTaskIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contract': {
      id: '/_app/contract'
      path: '/contract'
      fullPath: '/contract'
      preLoaderRoute: typeof AppContractRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data': {
      id: '/_app/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof AppDataRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/desktop': {
      id: '/_app/desktop'
      path: '/desktop'
      fullPath: '/desktop'
      preLoaderRoute: typeof AppDesktopRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/eval': {
      id: '/_app/eval'
      path: '/eval'
      fullPath: '/eval'
      preLoaderRoute: typeof AppEvalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/play': {
      id: '/_app/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof AppPlayRouteImport
      parentRoute: typeof AppRoute
    }
    '/harness/$taskId': {
      id: '/harness/$taskId'
      path: '/harness/$taskId'
      fullPath: '/harness/$taskId'
      preLoaderRoute: typeof HarnessTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worlds/$taskId': {
      id: '/worlds/$taskId'
      path: '/worlds/$taskId'
      fullPath: '/worlds/$taskId'
      preLoaderRoute: typeof WorldsTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppContractRoute: typeof AppContractRoute
  AppDataRoute: typeof AppDataRoute
  AppDesktopRoute: typeof AppDesktopRoute
  AppEvalRoute: typeof AppEvalRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppPlayRoute: typeof AppPlayRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppContractRoute: AppContractRoute,
  AppDataRoute: AppDataRoute,
  AppDesktopRoute: AppDesktopRoute,
  AppEvalRoute: AppEvalRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppPlayRoute: AppPlayRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  HarnessTaskIdRoute: HarnessTaskIdRoute,
  WorldsTaskIdRoute: WorldsTaskIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
